version: '3'
services:
  tw-server:
    image: ghcr.io/stephan418/tw-server/tw-server:latest
    ports:
      - 3042:3000
    environment: 
      - MONGO_HOST=mongodb
    
  mongodb:
    image: mongo
